### PR TITLE
Responsive desktop version

### PR DESCRIPTION
**Pull request by Sparktan24**
# Project requirements

- Make sure the desktop version looks like the one in sigma.
- Use media queries in your CSS file to make your version look like the template you selected (768px or wider).
- Should use Grid and Flexbox

For more details visit: https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @Sparktan24   , :wave:
### I'm Levy, your PR reviewer

Excellent work :sunglasses:  However, there are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
 - Good UI :heavy_check_mark: 
 - Linters are passing :heavy_check_mark: 
## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [x] Kindly make sure your project cards still look like the provided Figma design. :wink:  Kindly adjust your margins to meet the Figma design.

    - ### Your design
    image

    - ### Figma design
    image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sparktan24** [comment]
Hi, @levy002 Thanks for your review, just to be sure, do you mean these margins?
Margins

**Comment by levy002** [comment]
Hello, @Sparktan24. If you check carefully you will see that the project card is touching both ends but on the Figma design, there is a white space at both ends (horizontally). Kindly fix that and your project will be ready to be approved! Thank you for reaching out. :wink:

**Comment by Sparktan24** [comment]
Hi @levy002, Yes there is a margin but because of the gradient of the image it's barely noticeable I added a little more margin to make it easier to see I hope this is okay :smile: 
Margin between cards
ile:

**Review by Kamba56 — APPROVED** [review]
Hi @Sparktan24,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏
## Highlights
- [x] All linters passed
- [ ] Great and meaningful commit messages
- [ ] Great use of Github flow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
